server:
  port: 2023

spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: EmployeeServices
          uri: lb://EmployeeServices
          predicates:
            - Path=/employees/**
          filters:
            - name: CircuitBreaker
              args:
                name: EmployeeServices
                fallbackuri: forward:/employeefallback

        - id: DepartmentServices
          uri: lb://DepartmentServices
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DepartmentServices
                fallbackuri: forward:/departmentfallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream






